[workspace]
resolver = "3"
members = [
    "external/abs_buff",
    "external/abs_buff_stdio_adapt",
    "external/abs_buff_tokio_adapt",
    "external/abs_cancel",
    "external/abs_iter",
    "external/abs_sync",
    "external/atomex",
    "external/atomic_sync",
    "external/buffex",
    "external/gen_mcf_macro",
    "external/gen_mcf_test",

    "crates/rpc_core",
    "crates/rpc_transport_iroh",
    "crates/rpc_cs_demo",
]

[workspace.package]
edition = "2024"
authors = ["lino <lino_snsalias@outlook.com>"]

[workspace.dependencies]
funty = { version = "3.0.0-rc2", default-features = false }
pin-project = { version = "1.1.*" }
pin-utils = { version = "*" }
env_logger = { version = "0.11.*" }
log = { version = "0.4.*" }
futures-lite = { version = "2" }
compio = { version = "0.19.*", features = ["fs", "macros", "time"] }
thiserror = { version = "2.0", default-features = false }
