[package]
name = "mptp_cs_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
abs_art-bridge = { version = "0.2.2", default-features = false, features = ["backend-tokio"] }
mptp_core = { path = "../mptp_core" }
mptp_smux_iroh = { path = "../mptp_smux_iroh" }

anyhow = "1"
rmp-serde = "1.3.*"
iroh = "1.0.3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
