[package]
edition = "2024"
name = "msgpk_rpc_iroh"
version = "0.1.0"

description = "MsgPk RPC over IROH networks."
repository = "https://github.com/ljsnogard/msgpk_rpc_core"
keywords = ["rpc"]

license = "MIT/Apache-2.0"
readme = "README.md"

[dependencies]
msgpk_rpc_core = { path = "../rpc_core" }

abs_buff = { git = "https://gitee.com/lino_snsalias/abs_buff.git", branch = "dev/0.3.0", features = ["std_io"] }
abs_cancel = { git = "https://gitee.com/lino_snsalias/abs_cancel-rs.git" }
segm_buff = { git = "https://gitee.com/lino_snsalias/segm_buff.git", branch = "dev/0.3.0" }

anyhow = "1"
thiserror = "2"
iroh = "1.0.3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
